services:
  kotlin-spring:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/workspace:cached
      - $HOME/.ssh:/home/vscode/.ssh:ro
      - $HOME/.gitconfig:/home/vscode/.gitconfig:ro
    command: sleep infinity

  postgresql:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kotlin_spring_development
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
